server:
  port: 8082

spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/product-service-db
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    root: INFO
    org.springframework: DEBUG
